### ISSUE TITLE
vector operations type inference

### ISSUE THREAD

**Issue by melsman** [diku-dk/caddie#1]
We currently support both integers and reals as basic types in Caddie. Caddie should support vectorised operations.

We use `a` and `b` to range over type variables. Types take the following forms (not considering function types):

    f ::= real  |  int
    t ::= t x ... x t  |  []t  |  f  |  a

An atomic constraint `c` take the form:

    c ::= t :: S(f)  | t :: N

We use `C` to range over sets of atomic constraints:

    C ::= {c1,...,cn}

Type schemes (`s`) take the form:

    s ::= \/a1...an. t -> t with C

Many operations are generic in the structures they operate on but some operations, such as scalar multiplication (i.e., `*>`), are assumed to be applied to structures containing only reals as the underlying values in structures. Here are the type schemes of some of the operations:

    op +, *, - : \/a. a x a -> a with {a :: N}
    op *> : \/a. real x a -> a with {a :: S(real)}
    0    : \/a. a with {a :: N}
    ~    : \/a. a -> a with {a :: N}
    norm2sq : real x real -> real
    dprod : []real x []real -> real
    ...

## The Type System

The type system "infers" a set of constraints that need to be satisfied. We use `G` to range over type scheme assignments.  The type system allows inferences among sentences of the form `G |- e : t, C`. Here are some of the rules:

    G |- e1 : t1, C1    ...    G |- en : tn, Cn 
    ---------------------------------------------
    G |- (e1,...,en) : (t1,...,tn), C1 u ... u Cn

    G(x) ≥ t1 -> t2, C     G |- e : t1, C1 
    ---------------------------------------
    G |- x e : t2, C1 u C

## Constraint Resolution

Constraints are rewritten (i.e., resolved) as follows:

    {t[] :: N} u C   ~>   {t :: N} u C
    {f :: N} u C   ~>   C
    {(t1,...,tn) :: N} u C   ~>   { t1 :: N, ...,   tn :: N} u C
    {t[] :: S(f)} u C   ~>   {t :: S(f)} u C
    {f :: S(f)} u C   ~>   C
    {(t1,...,tn) :: S(f)} u C   ~>   { t1 :: S(f), ...,   tn :: S(f)} u C

## Well-Typed Expressions

An expression `e` is _well-typed_ and has type `t` if `|- e : t, C` and `C ~>* Ø`.

## Some Questions

Would this design be valuable? Here are some issues to consider before we take a decision:

1. We need to compile operations such as `~ ([1,2,3],10)` into intermediate language representations `(map (op ~) [1,2,3], ~10)` as the source expression is permitted by the type system.
2. We could later support automatic vectorisation of other operations such as `sin [1,2,4]`. Initially, we could give the type `real -> real` to the `sin` operations, instead of the more liberal constrained type scheme `\/a. a -> a with {a :: S(real)}`.

**Comment by melsman** [comment]
What do you think @zfnmxt ?

**Comment by athas** [comment]
One problem is that `int` is not actually a field (no multiplicative inverse).

**Comment by melsman** [comment]
Gee - of course. But many of the operations are defined on integers, so
it's mostly about refining the terminology used in the definitions, I
believe...

søn. 18. jul. 2021 kl. 23.42 skrev Troels Henriksen <
***@***.***>:

**Comment by zfnmxt** [comment]
What `VS(f) |- t` is really expressing is just the underlying scalar
type of a larger type.  In this view I don't see any issues with
adding the axiom

```
-------------- 
VS(int) |- int 
```
 
(although maybe we should change it to `S(f) |- t`).  We just have to
ensure that at differentiation time we exclusively use the operations
on vector spaces.

1. Operations like `~ ([1,2,3],10)` should/need to be
supported since `R^3 x R` is clearly a vector space and negation is a vector space operation 
(and we should support all vector spaces that can be expressed with the constraints
of our type system). But it seems (at least this example) straightforward to compile, maybe something like:
```
compile (f, e) = 
  let compile' int = f
      compile' real = f
      compile' (array t)  = map (compile' t)
      compile' (pairs ts) = (\fs (e1,..,en) -> (fs[1] e1, .., fs[n] en)) (map compile' ts)
  in compile' (typeOf e) e
```

2. This is neat!

3. Shouldn't we have `dprod : {\/a. a x a -> real, VS(real) |- a}`?
   With our current types, we should be able to define a dot/inner
   product on any `a`, something like:
   
```
dprod (real x, real y) = x * y
dprod (array es1, array es2) = sum (zipWith dprod es1 es2)
dprod ((e1,...,en),(d1,..,dn)) = dprod(e1,d1) + ... + dprod(d1, dn)
```

4. The utility of allowing different underlying scalars hinges on how
   useful it is to overload these operators to work on different
   scalars. The details of how reduces/relations will work is still a
   bit murky to me, but I think being able to express arbitrary
   expressions will likely be a necessity and that only providing
   specialized relation constructors (e.g., a constructor which
   specifies a convolutional relation) which only take integers as
   arguments may be too restrictive, but I'm uncertain.

   In the case where the user needs to specify a relation explicitly
   (i.e., as a list of pairs) doing so as a computation is far
   superior. This also brings to mind the fact that any explicit
   relation can be inverted, which means it can be used as a 
   fallback in the case where a user specifies a relation
   we don't know how to invert.
   
I think the design is promising and captures what we're trying to
express well (namely that *all* vectors can be manipulated with these
operations).
